spring.application.name=Backend-Clinica-DentalPro
server.port=8080

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-twilight-unit-aqoso08t-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NIO7bEGis0lA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=DentalProSecretKey2025XYZABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijk
jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# ─── EMAIL (Gmail SMTP) ────────────────────────────────────────────────────────

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=principemerinosheila@gmail.com
spring.mail.password=gvom akvd tqce qfdw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# En dev=true el código se incluye en la respuesta JSON (útil sin SMTP configurado)
app.mail.dev-mode=false